DOMAIN = "ha_easylog_cloud"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
PLATFORMS = ["sensor"]
STARTUP_MESSAGE = "Starting EasyLog Cloud integration"
BINARY_SENSOR = "binary_sensor"
SENSOR = "sensor"
SWITCH = "switch"
DEFAULT_NAME = "easylog_cloud"