name: Draft a release note
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
permissions:
  contents: write
  issues: read
  pull-requests: read
jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Run release-drafter
        uses: release-drafter/release-drafter@v5.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
